siteTitle = "APALHU"
siteDescr = "Asociación Humanista."
siteAuthor = "APALHU.ORG"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/website"
