siteTitle = "APALHU"
siteDescr = ""
siteAuthor = "www.apalhu.org"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "mailto:apalhu.org@gmail.com"
siteRssUrl = "#"
siteFacebook = "https://www.facebook.com/Associaci%C3%B3-per-a-lHumanisme-563001543895860"

googleAnalyticsId = ""

linkPrefix = "/website"
