siteTitle = "APALHU"
siteDescr = "Associació per a 'humanisme"
siteAuthor = "www.apalhu.org"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/website"
